# Generated by Django 3.1.3 on 2020-12-03 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_Answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Demographic', to=settings.AUTH_USER_MODEL, to_field='username', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demographic_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_question_no', models.PositiveIntegerField()),
                ('demo_question', models.CharField(max_length=5000)),
                ('demo_field_type', models.CharField(choices=[('Optional', 'Optional'), ('Mandatory', 'Mandatory')], default='Mandatory', max_length=10)),
            ],
            options={
                'ordering': ['demo_question_no'],
            },
        ),
        migrations.CreateModel(
            name='Initial_ISQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, to_field='username', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ISQ_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question', models.CharField(max_length=5000)),
                ('question_type', models.CharField(choices=[('Options', 'Options'), ('YESNO', 'YES/NO'), ('Slider', 'Slider'), ('Text', 'Text'), ('Number', 'Number')], default='Text', max_length=10)),
            ],
            options={
                'ordering': ['question_no'],
            },
        ),
        migrations.CreateModel(
            name='Demographic_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_answer', models.PositiveIntegerField()),
                ('demo_answer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Demographics', to=settings.AUTH_USER_MODEL)),
                ('demo_main_question_set', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ISQ', to='Programs.demographic')),
                ('demo_question_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_question_nme_for_answer', to='Programs.demographic_questions')),
            ],
        ),
        migrations.CreateModel(
            name='ISQAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveIntegerField()),
                ('answer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_user', to=settings.AUTH_USER_MODEL)),
                ('main_question_set', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ISQ', to='Programs.initial_isq')),
                ('question_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_nme_for_answer', to='Programs.isq_questions')),
            ],
            options={
                'unique_together': {('question_name', 'answer_by')},
            },
        ),
    ]
