# Generated by Django 3.1.3 on 2020-12-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographic_answers',
            name='demo_answer_by',
        ),
        migrations.RemoveField(
            model_name='demographic_answers',
            name='demo_main_question_set',
        ),
        migrations.RemoveField(
            model_name='demographic_answers',
            name='demo_question_name',
        ),
        migrations.DeleteModel(
            name='Demographic',
        ),
        migrations.DeleteModel(
            name='Demographic_answers',
        ),
        migrations.DeleteModel(
            name='Demographic_Questions',
        ),
    ]
