# Generated by Django 3.1.3 on 2020-11-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_auto_20201123_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='isq_questions',
            name='question_type',
            field=models.CharField(choices=[('Options', 'Options'), ('YESNO', 'YES/NO'), ('Slider', 'Slider'), ('Text', 'Text'), ('Number', 'Number')], default='Text', max_length=10),
        ),
    ]
