# Generated by Django 3.1.3 on 2020-11-23 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Programs', '0003_isq_questions_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_Answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Demographic', to=settings.AUTH_USER_MODEL, to_field='username', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demographic_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_question_no', models.PositiveIntegerField()),
                ('demo_question', models.CharField(max_length=5000)),
                ('demo_field_type', models.CharField(choices=[('Optional', 'Optional'), ('Mandatory', 'Mandatory')], default='Mandatory', max_length=10)),
            ],
            options={
                'ordering': ['demo_question_no'],
            },
        ),
        migrations.CreateModel(
            name='Demographic_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_answer', models.PositiveIntegerField()),
                ('demo_answer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Demographics', to=settings.AUTH_USER_MODEL)),
                ('demo_main_question_set', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ISQ', to='Programs.demographic')),
                ('demo_question_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_question_nme_for_answer', to='Programs.demographic_questions')),
            ],
        ),
    ]
