version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
        - "6379:6379"
    expose:
        - "6379"
  web:
      build:
        context: .
        dockerfile: docker/dockerfile_backend
      container_name: docker-django-vue-backend
      image: app
      restart: always
#      command: ./docker/backend_setup.sh
      command: python backend/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      links:
        - redis
#      depends_on:
#        - migration
  vue:
    build:
      context: .
      dockerfile: docker/frontendDockerFile
    container_name: docker-django-vue-frontend
    command: npm run serve
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - web

  migration:
   build: .
   image: app
   command: python backend/manage.py migrate
   volumes:
     - .:/code
   depends_on:
     - make_migration
  make_migration:
         build: .
         image: app
         command: python backend/manage.py makemigrations
         volumes:
           - .:/code
