# Generated by Django 2.2.28 on 2023-01-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Description', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, default='Dairy.png', null=True, upload_to='profile_pics')),
                ('price', models.IntegerField(default=0)),
                ('likes', models.ManyToManyField(related_name='likes_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(max_length=15)),
                ('Price', models.IntegerField(default=0)),
                ('Site_URL', models.URLField(max_length=70)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Features', models.TextField()),
                ('Course_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Course', to='Aggregator.Course')),
            ],
        ),
    ]
