# Generated by Django 2.2.28 on 2023-01-09 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Designation', models.CharField(max_length=10)),
                ('Git', models.URLField(max_length=50)),
                ('Facebook', models.URLField(max_length=50)),
                ('Email', models.URLField(max_length=50)),
                ('phone_Number', models.CharField(max_length=10)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Category',
            field=models.CharField(default='Computers', max_length=15),
        ),
        migrations.CreateModel(
            name='Testmonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=300)),
                ('Description', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, default='Dairy.png', null=True, upload_to='profile_pics')),
                ('likes', models.ManyToManyField(related_name='likes_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
