# Generated by Django 3.1.3 on 2020-12-10 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_ISQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fuser', to=settings.AUTH_USER_MODEL, to_field='username', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FISQ_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question', models.CharField(max_length=5000)),
                ('question_type', models.CharField(choices=[('Options', 'Options'), ('YESNO', 'YES/NO'), ('Slider', 'Slider'), ('Text', 'Text'), ('Number', 'Number')], default='Text', max_length=10)),
            ],
            options={
                'ordering': ['question_no'],
            },
        ),
        migrations.CreateModel(
            name='FISQAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveIntegerField()),
                ('answer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_Fuser', to=settings.AUTH_USER_MODEL)),
                ('main_question_set', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FISQ', to='FPrograms.final_isq')),
                ('question_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_name_for_Fanswer', to='FPrograms.fisq_questions')),
            ],
            options={
                'unique_together': {('question_name', 'answer_by')},
            },
        ),
    ]
