# Generated by Django 2.2.17 on 2020-11-11 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('student', models.ManyToManyField(blank=True, null=True, related_name='Student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
