# Generated by Django 2.2.17 on 2020-11-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.IntegerField(choices=[(0, 'enroll'), (1, 'start'), (2, 'middle'), (3, 'completed'), (4, 'Un-enroll')], default=4),
        ),
    ]
