# Generated by Django 2.2.17 on 2020-11-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_program_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=250)),
                ('video_number', models.IntegerField()),
                ('slug', models.SlugField()),
                ('program_video_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_video', to='dairy.Program')),
            ],
        ),
    ]
