# Generated by Django 2.2.17 on 2020-11-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0003_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='slug',
            field=models.URLField(max_length=300),
        ),
    ]
