# Generated by Django 3.1.3 on 2020-12-10 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FWBMNU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FWBMNU', to=settings.AUTH_USER_MODEL, to_field='username', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FWBMNU_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveIntegerField()),
                ('question', models.CharField(max_length=5000)),
                ('question_type', models.CharField(choices=[('Options', 'Options'), ('YESNO', 'YES/NO'), ('Slider', 'Slider'), ('Text', 'Text'), ('Number', 'Number')], default='Text', max_length=10)),
            ],
            options={
                'ordering': ['question_no'],
            },
        ),
        migrations.CreateModel(
            name='FWBMNU_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_FWBMNU', to=settings.AUTH_USER_MODEL)),
                ('main_question_set', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FWBMNU', to='FWellbeingModelNU.fwbmnu')),
                ('question_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FWBMNU_name_for_answer', to='FWellbeingModelNU.fwbmnu_questions')),
            ],
        ),
    ]
