# Generated by Django 3.1.3 on 2021-02-06 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Description', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, default='Dairy.png', null=True, upload_to='profile_pics')),
                ('likes', models.ManyToManyField(related_name='likes_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DairyLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DairyNumber', models.IntegerField(default=1)),
                ('Text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week_number', models.IntegerField()),
                ('Week_name', models.CharField(max_length=200)),
                ('Course_Week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_week', to='Courses.course')),
                ('view_status', models.ManyToManyField(related_name='View_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_URL', models.URLField(max_length=3000)),
                ('Video_Name', models.CharField(max_length=300)),
                ('Video_Description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('Dairy_Description', models.TextField(default='please add your dairy after seeing video')),
                ('Video_week', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Video_Week', to='Courses.week')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Course', to='Courses.course')),
                ('Enrolled_User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Enrolled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Dairy_Text', models.TextField()),
                ('Dairy_head', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Dairy_label', to='Courses.dairylabel')),
                ('Wrote_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Dairy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Date', 'Wrote_by')},
            },
        ),
    ]
