# Generated by Django 3.1.3 on 2021-02-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dairy',
            old_name='Dairy_head',
            new_name='Dairy_label',
        ),
    ]
