# Generated by Django 3.1.3 on 2021-02-05 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question', models.CharField(max_length=5000)),
                ('question_type', models.CharField(choices=[('Options', 'Options'), ('YESNO', 'YES/NO'), ('Slider', 'Slider'), ('Text', 'Text'), ('Number', 'Number')], default='Text', max_length=10)),
                ('quetions_free_text', models.TextField(blank=True, null=True)),
                ('question_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topic_qsn', to='Questions.topic', unique=True)),
            ],
            options={
                'ordering': ['question_no'],
            },
        ),
        migrations.CreateModel(
            name='Initial_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_initial', to=settings.AUTH_USER_MODEL, to_field='username', unique=True)),
                ('Course_initial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Initial_course', to='Questions.topic', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Final_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_final', to=settings.AUTH_USER_MODEL, to_field='username', unique=True)),
                ('Course_Final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Final_course', to='Questions.topic', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Initial_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Initial_answer', models.PositiveIntegerField()),
                ('Initial_answer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_answer', to=settings.AUTH_USER_MODEL)),
                ('Initial_main_question_set', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Initial_answers', to='Questions.initial_answer')),
                ('Initial_question_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Initial_question', to='Questions.questions')),
            ],
            options={
                'unique_together': {('Initial_question_name', 'Initial_answer_by')},
            },
        ),
        migrations.CreateModel(
            name='Final_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Final_answer', models.PositiveIntegerField()),
                ('Final_answer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Final_answer', to=settings.AUTH_USER_MODEL)),
                ('Final_main_question_set', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Final_answers', to='Questions.final_answer')),
                ('Final_question_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Final_question', to='Questions.questions')),
            ],
            options={
                'unique_together': {('Final_question_name', 'Final_answer_by')},
            },
        ),
    ]
