# Generated by Django 3.1.3 on 2021-02-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topic_qsn', to='Questions.topic'),
        ),
    ]
