# Generated by Django 3.1.3 on 2021-02-05 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_auto_20210205_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.TextField(blank=True, null=True)),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topic_Label', to='Questions.topic')),
            ],
        ),
    ]
