# Generated by Django 3.1.3 on 2021-02-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='label_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
