# Generated by Django 3.1.3 on 2021-02-08 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questions', '0004_labels_label_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intial_BaseLine_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Initial_answer', models.TextField(blank=True, default=1, null=True)),
                ('Answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_initial', to=settings.AUTH_USER_MODEL, to_field='username', unique=True)),
                ('Course_initial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Initial_course', to='Questions.topic', unique=True)),
                ('Initial_question_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Initial_question', to='Questions.questions', unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='initial_answers',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='initial_answers',
            name='Initial_answer_by',
        ),
        migrations.RemoveField(
            model_name='initial_answers',
            name='Initial_main_question_set',
        ),
        migrations.RemoveField(
            model_name='initial_answers',
            name='Initial_question_name',
        ),
        migrations.DeleteModel(
            name='Initial_Answer',
        ),
        migrations.DeleteModel(
            name='Initial_Answers',
        ),
    ]
