# Generated by Django 3.1.3 on 2021-02-08 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questions', '0006_auto_20210208_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intial_baseline_answer',
            name='Answered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_initial', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
