# Generated by Django 2.2.28 on 2023-01-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230110_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
