# Generated by Django 3.1.3 on 2020-12-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demographics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demographic_questions',
            options={'ordering': ['question_no']},
        ),
        migrations.RenameField(
            model_name='demographic',
            old_name='demo_Answered_by',
            new_name='Answered_by',
        ),
        migrations.RenameField(
            model_name='demographic_answers',
            old_name='demo_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='demographic_answers',
            old_name='demo_answer_by',
            new_name='answer_by',
        ),
        migrations.RenameField(
            model_name='demographic_answers',
            old_name='demo_main_question_set',
            new_name='main_question_set',
        ),
        migrations.RenameField(
            model_name='demographic_answers',
            old_name='demo_question_name',
            new_name='question_name',
        ),
        migrations.RenameField(
            model_name='demographic_questions',
            old_name='demo_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='demographic_questions',
            old_name='demo_question_no',
            new_name='question_no',
        ),
        migrations.RenameField(
            model_name='demographic_questions',
            old_name='demo_field_type',
            new_name='question_type',
        ),
    ]
