# Generated by Django 3.1.3 on 2020-12-15 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demographics', '0003_auto_20201208_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic_questions',
            name='question_field',
            field=models.CharField(choices=[('Number', 'Number'), ('YESNO', 'YES/NO'), ('TEXT', 'TEXT')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='demographic_answers',
            name='main_question_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Demo', to='Demographics.demographic'),
        ),
    ]
