# Generated by Django 3.1.3 on 2020-12-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demographics', '0005_auto_20201215_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic_questions',
            name='question_field',
            field=models.CharField(choices=[('Gender', 'Gender'), ('Number', 'Number'), ('YESNO', 'YES/NO'), ('TEXT', 'TEXT')], default='Mandatory', max_length=10),
        ),
    ]
